### ISSUE TITLE
How can I disable global/base classname generation?

### ISSUE THREAD

**Issue by badsyntax** [tailwindlabs/tailwindcss-typography#116]
Hi, I'd like to use the `tailwindcss-typography` component in my css (using css modules):

```css
.variant-prose {
  @apply prose
    lg:prose-xl;
}
```

This works great but the plugin also seems to generate global unwanted `.prose` classnames. 

My base stylesheet is defined as :

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
````

My `tailwind.config.js` file:

```js
const typography = require('@tailwindcss/typography');

module.exports = {
  purge: ['./pages/**/*.tsx', './features/**/*.tsx'],
  darkMode: false, 
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [typography],
};
```

This is the generated global css:

```css
.prose{color:#374151;max-width:65ch}.prose a{color:#111827;text-decoration:underline;font-weight:500}.prose strong{color:#111827;font-weight:600}
/* etc */
```

How can I disable the global `.prose` classname generation? It just adds bloat to my stylesheet.
