### ISSUE TITLE
dark:prose-invert not included in Tailwind standalone version

### ISSUE THREAD

**Issue by danjac** [tailwindlabs/tailwindcss-typography#233]
### What version of @tailwindcss/typography are you using?

Tailwind standalone release v3.0.13

### What version of Node.js are you using?

n/a

### What browser are you using?

Firefox, Chrome

### What operating system are you using?

Linux, Android

### Reproduction repository

https://github.com/danjac/jcasts

### Describe your issue

The standalone Tailwind which includes typography does not include **dark:prose-invert**, so all colors are rendered unreadable in dark mode. The current workaround is to provide custom CSS.

e.g

```
<div class="prose dark:prose-invert">
content...
</div>

```

**Comment by minijoo** [comment]
Does this mean prose-invert is unavailable at this moment?

**Comment by danjac** [comment]
> Does this mean prose-invert is unavailable at this moment?

Yes. I have to use workaround in app.css as prose-invert does nothing:

```css

    @media (prefers-color-scheme: dark) {
        .prose {
            color: theme('colors.gray.300') !important;
        }
        .prose ol > li::marker,
        .prose ul > li::marker {
            color: theme('colors.gray.300') !important;
        }
        .prose hr {
            border-color: theme('colors.gray.500') !important;
        }
        .prose a,
        .prose blockquote,
        .prose figcaption,
        .prose pre,
        .prose code,
        .prose {
            color: theme('colors.gray.300') !important;
        }
        .prose strong,
        .prose h1,
        .prose h2,
        .prose h3,
        .prose h4,
        .prose h5 {
            color: theme('colors.gray.200') !important;
        }
    }

```
