### ISSUE TITLE
`legacy` mode not working for `prose-{element}` modifiers

### ISSUE THREAD

**Issue by Folyd** [tailwindlabs/tailwindcss-typography#258]
### What version of @tailwindcss/typography are you using?

The latest version typography installed by Tailwind standalone CLI

### What version of Node.js are you using?

No Node.js. I'm using the latest Tailwind standalone CLI

### What browser are you using?

Safari and Edge

### What operating system are you using?

macOS 10.15.7

### Reproduction repository

https://github.com/zineland/zine

### Describe your issue

After I enable the `legacy` mode according to https://github.com/tailwindlabs/tailwindcss-typography/issues/255, Tawilwind still renders `prose-h1:text-center`  with `:where` clauses.

```html
<article class="prose prose-h1:text-center">
</article>
```

```css
.prose-h1\:text-center :is(:where(h1):not(:where([class~=not-prose] *))) {
    text-align: center;
}
```
