### ISSUE TITLE
Unexpected multiple `font-family` declarations

### ISSUE THREAD

**Issue by timothyis** [tailwindlabs/tailwindcss-typography#271]
### What version of @tailwindcss/typography are you using?

0.5.2

### What version of Node.js are you using?

v16.13.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/timothyis/tailwind-typography-repro

### Describe your issue

When using the `prose` class to use the pre-formatted styling from tailwind-typography (and configuration for both serif and sans-serif fonts in `tailwind.config.js`, along with config to change heading font-families), tailwind generates classes for headings with multiple `font-family` declarations instead of just one declaration with a list of values.

For example, with the following config:

```js
const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
    content: [
        "./pages/**/*.{js,ts,jsx,tsx}",
        "./components/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        fontFamily: {
            sans: ['Source Sans Pro', ...defaultTheme.fontFamily.sans],
            serif: ['Source Serif Pro', ...defaultTheme.fontFamily.serif],
        },
    },
     extend: {
            typography: (theme) => ({
                DEFAULT: {
                    css: {
                        fontSize: theme('fontSize.xl')[0],
                        h1: {
                            fontFamily: theme('fontFamily.serif'),
                            fontWeight: theme('fontWeight.semibold'),
                            fontSize: theme('fontSize.5xl')[0],
                            lineHeight: '1.2',
                            margin: '0 0 0.5em 0',
                        }
                    }
                }
            })
        }
    },
    plugins: [
        require('@tailwindcss/typography')
    ],
}
```
(extended in the repro repo)

Tailwind generates the following for h1 stylings:
```css
.prose :where(h1):not(:where([class~="not-prose"] *)) {
    color: var(--tw-prose-headings);
    font-weight: 600;
    font-size: 3rem;
    margin-top: 0;
    margin-bottom: 0.8888889em;
    line-height: 1.2;
    font-family: Source Serif Pro;
    font-family: ui-serif;
    font-family: Georgia;
    font-family: Cambria;
    font-family: "Times New Roman";
    font-family: Times;
    font-family: serif;
    margin: 0 0 0.5em 0;
}
```
In which case, this block will render the heading in `serif`, and not the desired `Source Serif Pro`.

This may be a case of myself misunderstanding how this should be configured, but I believe I've followed the docs correctly to create the config and so I'm creating this as a bug.

Please let me know if I can provide any further information, and thanks in advance!
