### ISSUE TITLE
Too much space between figcaption and code block (pre)

### ISSUE THREAD

**Issue by ramrami** [tailwindlabs/tailwindcss-typography#304]
### What version of @tailwindcss/typography are you using?

v0.5.9

### What version of Node.js are you using?

v16.13.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/iEhifXieK7

### Describe your issue

When wrapping a code block (pre) inside a figure and adding a figcaption, too much margin is added between the code block and the caption. I expected the space to be the same as the one used for an image+caption.

It looks like there is some specificity issue between these two rules: 

```css
.prose :where(pre):not(:where([class~="not-prose"] *)) {
    margin-top: 1.7142857em;
    margin-bottom: 1.7142857em;
}
```

and

```css
.prose :where(figure > *):not(:where([class~="not-prose"] *)) {
    margin-top: 0;
    margin-bottom: 0;
}
```

Thanks.
