### ISSUE TITLE
@apply prose is failing the first- and last-child selectors

### ISSUE THREAD

**Issue by mario-neuhold** [tailwindlabs/tailwindcss-typography#351]
### What version of @tailwindcss/typography are you using?

0.5.12

### What version of Node.js are you using?

20

### What browser are you using?

Chrome and Edge

### What operating system are you using?

Win11

### Reproduction repository

https://play.tailwindcss.com/WJj0WzrLV6

### Describe your issue

When using `@apply prose` on a class e.g. `.is-style-prose` the generated css for removing the top margin of its first child looks like this:
```css
.is-style-prose
  :where(
    /* this should be .is-style-prose instead of .prose */
    .prose > :first-child 
  ):not(
    :where(
      [class~="not-prose"],[class~="not-prose"] *
    )
  ) {
    margin-top: 0;
  }
```
So the wrong class name in the `:where()` clause causes the top margin from h2, h3, .. to not being removed. Same goes for the bottom margins of the last-child of the prose class.
See https://play.tailwindcss.com/WJj0WzrLV6
