### ISSUE TITLE
Variable colors with <alpha-value> not working with theme function in Typography

### ISSUE THREAD

**Issue by macmladen** [tailwindlabs/tailwindcss-typography#360]
### What version of @tailwindcss/typography are you using?

0.5.7

### What version of Node.js are you using?

v20.16.0

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/Vy3U1DPfEc

### Describe your issue

I found that using variables in `tailwind.config.js` a described in [documentation](https://tailwindcss.com/docs/customizing-colors#using-css-variables) works with **Tailwind** itself but it does not work in plugin **Typography**.

That is demonstrated in the playground: https://play.tailwindcss.com/Vy3U1DPfEc

## The problem

Here, using Tailwind class generated from the custom colors defined by variables work: `text-body/50` using `--drupal-red` and 50% opacity:

```css
.text-body\/50 {
  color: rgb(var(--drupal-red) / 0.5);
}
```

The same is not working with `.prose` at all: when compiled, it retains `<alpha-value>` as literal

```css
--tw-prose-body: rgb(var(--drupal-red) / <alpha-value>);
```

## Files (partial)

`style.css`
```css
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";

@layer base {
  :root {
    //-- Drupal Color system --
    // Primary Color Palette
    --drupal-blue: 0 156 222;
    --drupal-dark-blue: 0 106 169;
    --drupal-navy: 18 40 95;

    // Secondary Color Palette
    --drupal-light-blue: 204 237 249;
    --drupal-black: 0 0 0;
    --drupal-white: 255 255 255;

    // Tertiary Color Palette
    --drupal-purple: 204 237 249;
    --drupal-yellow: 255 196 35;
    --drupal-red: 244 99 81;
    --drupal-green: 57 118 43;
  }
}

```

`tailwind.config.js`
```js
module.exports = {
  theme: {
    extend: {
      colors: {
        body:  'rgb(var(--drupal-red) / <alpha-value>)',
      },
      typography: (theme) => ({
        DEFAULT: {
          css: {
            // This works
            // '--tw-prose-body': 'rgb(var(--drupal-red))',
            // But I want the colors.body used here:
            '--tw-prose-body': theme('colors.body'),
          },
        },
      }),
    },
  },
  // ...
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
```
