### ISSUE TITLE
How to exclude GFM task list :before "bullet"?

### ISSUE THREAD

**Issue by brianakidd** [tailwindlabs/tailwindcss-typography#55]
Is there a way to support Github-Flavored Markdown task list without the ul>li:before "bullet"?  Here is how it is rendering:

<img width="308" alt="Screen Shot 2020-08-12 at 6 41 51 PM" src="https://user-images.githubusercontent.com/6431835/90075523-9dac2d80-dccb-11ea-803f-08bfbfcea989.png">

**Comment by wildpow** [comment]
My hack:
```css
 article ul .task-list-item {
    ::before {
      display: none;
    }
  }
```
