### ISSUE TITLE
Empty content in pseudo :before class is removed

### ISSUE THREAD

**Issue by danrocha** [tailwindlabs/tailwindcss-typography#59]
If I add this to the config:

```js
module.exports = {
  theme: {
    typography: (theme) => ({
      default: {
        css: [
            'h2:before': {
              display: 'block',
              content: '',
              width: theme('width.24'),
              marginBottom: theme('margin.2'),
              borderTopWidth: theme('borderWidth.2'),
              borderTopColor: theme('colors.blue.400'),
            },
          },
        ],
      },
     ...
}
```

The empty `content` property gets removed and results in the invalid CSS:

```css
h2::before {
	display: block;
	content: ;  /* invalid!! */
	width: 6rem;
	margin-bottom: 0.5rem;
	border-top-width: 2px;
	border-top-color: #63b3ed;
}
```

Any ideas on how to add an empty `content` property to the `:before` pseudo class?
